
package org.soap.stub;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServerSoap", targetNamespace = "http://server.soap.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerSoap {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://server.soap.org/", className = "org.soap.stub.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://server.soap.org/", className = "org.soap.stub.AddStudentResponse")
    @Action(input = "http://server.soap.org/ServerSoap/addStudentRequest", output = "http://server.soap.org/ServerSoap/addStudentResponse")
    public void addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateStudent", targetNamespace = "http://server.soap.org/", className = "org.soap.stub.UpdateStudent")
    @ResponseWrapper(localName = "updateStudentResponse", targetNamespace = "http://server.soap.org/", className = "org.soap.stub.UpdateStudentResponse")
    @Action(input = "http://server.soap.org/ServerSoap/updateStudentRequest", output = "http://server.soap.org/ServerSoap/updateStudentResponse")
    public void updateStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStudent", targetNamespace = "http://server.soap.org/", className = "org.soap.stub.DeleteStudent")
    @ResponseWrapper(localName = "deleteStudentResponse", targetNamespace = "http://server.soap.org/", className = "org.soap.stub.DeleteStudentResponse")
    @Action(input = "http://server.soap.org/ServerSoap/deleteStudentRequest", output = "http://server.soap.org/ServerSoap/deleteStudentResponse")
    public void deleteStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllStudents", targetNamespace = "http://server.soap.org/", className = "org.soap.stub.GetAllStudents")
    @ResponseWrapper(localName = "getAllStudentsResponse", targetNamespace = "http://server.soap.org/", className = "org.soap.stub.GetAllStudentsResponse")
    @Action(input = "http://server.soap.org/ServerSoap/getAllStudentsRequest", output = "http://server.soap.org/ServerSoap/getAllStudentsResponse")
    public String getAllStudents();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.soap.stub.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://server.soap.org/", className = "org.soap.stub.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://server.soap.org/", className = "org.soap.stub.GetStudentResponse")
    @Action(input = "http://server.soap.org/ServerSoap/getStudentRequest", output = "http://server.soap.org/ServerSoap/getStudentResponse")
    public Student getStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
