
package org.soap.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServerSoapService", targetNamespace = "http://server.soap.org/", wsdlLocation = "http://localhost:8080/ws/students.wsdl?wsdl")
public class ServerSoapService
    extends Service
{

    private static final URL SERVERSOAPSERVICE_WSDL_LOCATION;
    private static final WebServiceException SERVERSOAPSERVICE_EXCEPTION;
    private static final QName SERVERSOAPSERVICE_QNAME = new QName("http://server.soap.org/", "ServerSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/students.wsdl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERSOAPSERVICE_WSDL_LOCATION = url;
        SERVERSOAPSERVICE_EXCEPTION = e;
    }

    public ServerSoapService() {
        super(__getWsdlLocation(), SERVERSOAPSERVICE_QNAME);
    }

    public ServerSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERSOAPSERVICE_QNAME, features);
    }

    public ServerSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVERSOAPSERVICE_QNAME);
    }

    public ServerSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERSOAPSERVICE_QNAME, features);
    }

    public ServerSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerSoap
     */
    @WebEndpoint(name = "ServerSoapPort")
    public ServerSoap getServerSoapPort() {
        return super.getPort(new QName("http://server.soap.org/", "ServerSoapPort"), ServerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerSoap
     */
    @WebEndpoint(name = "ServerSoapPort")
    public ServerSoap getServerSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.soap.org/", "ServerSoapPort"), ServerSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERSOAPSERVICE_EXCEPTION!= null) {
            throw SERVERSOAPSERVICE_EXCEPTION;
        }
        return SERVERSOAPSERVICE_WSDL_LOCATION;
    }

}
